[versions]
# Minecraft
minecraft = "26.2"
minecraftRange = "[26.2, )"
neoforge = "26.2.0.75"
neoforgeRange = "[26.2.0.75, )"
loaderRange = "[6, )"

# Plugins
moddev = "2.0.144"
kotlin = "2.4.0"

# Dependencies
kff = "6.3.0"
kffRange = "[6.3.0, )"

[libraries]
kff = { module = "thedarkcolour:kotlinforforge-neoforge", version.ref = "kff" }

[plugins]
moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }